aql-check:
  stage: test
  tags:
    - test
  script:
    - git submodule add --force git@scm.cms.hu-berlin.de:rueg-pd/rueg-ci/rueg-runner.git tests
    - git submodule update --remote
    - echo "Running check on latest changes ..."
    - bash tests/aql/check_changes.sh
  only:
    changes:
      - "{exb,ptb,conll}/RUEG/P*/*/*.{exb,ptb,conll,conllu,txt}"
