validity-check:
  stage: test
  tags:
    - test
  script:
    - git submodule add git@scm.cms.hu-berlin.de:rueg-pd/rueg-ci/rueg-runner.git tests
    - echo "Checking updated exmaralda files (if any) for validity"
    - bash tests/valid_exb/test.sh
  only:
    changes:
      - "exb/RUEG/P*/*/*.exb"
