manual-exmaralda-check:
  stage: test
  tags:
    - test
  script:
    - git submodule add --force git@scm.cms.hu-berlin.de:rueg-pd/rueg-ci/rueg-runner.git tests
    - tests/aql/annatto-cli tests/manual-checks/all-exb/import_exb.xml
  rules:
    - when: manual
      allow_failure: true
manual-conll-check:
  stage: test
  tags:
    - test
  script:
    - git submodule add --force git@scm.cms.hu-berlin.de:rueg-pd/rueg-ci/rueg-runner.git tests
    - tests/aql/annatto-cli tests/manual-checks/all-conll/import_conll.xml
  rules:
    - when: manual
      allow_failure: true
