hidden-tier-check:
  stage: test
  tags:
    - test
  script:
    - git submodule add --force git@scm.cms.hu-berlin.de:rueg-pd/rueg-ci/rueg-runner.git tests
    - echo "Checking for hidden tiers"
    - bash tests/hidden-tiers/test.sh
  only:
    changes:
      - "exb/RUEG/P*/*/*.exb"
