plausibility-check:
  stage: test
  tags:
    - test
  script:
    - echo "Checking number of changed files for plausibility"
    - echo $(pwd)
    - echo $CI_COMMIT_MESSAGE
    - bash tests/plausibility/test.sh
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /#plausible/
