plausibility-check:
  stage: test
  tags:
    - test
  script:
    - bash submodule_init.sh
    - echo "Checking number of changed files for plausibility"
    - bash tests/plausibility/test.sh
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /#plausible/
